# Generated by Django 3.2 on 2023-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_auto_20230505_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/blank-user-profile.png', upload_to='profile_images'),
        ),
    ]
